name: CI

on:
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Building ..."

  test: 
    needs: build
    runs-on: ubuntu-latest

    strategy:
      # Disable to prevent exiting on first failed test
      fail-fast: false
      # Run 4 job instances to execute tests in parallel
      # https://www.testmo.com/guides/github-actions-parallel-testing/
      matrix:
        # Job instances - make them available as env vars in this job
        ci_index: [0, 1, 2, 3]
        ci_total: [4]

    steps:
        # This uses the actions/checkout action to clone your repository.
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          # sets up the specified Node version, and
          node-version: 22.x
          # caches npm dependencies to speed up the workflow.
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run unit-tests
        run: yarn test:unit
        env:
          CI_TOTAL: ${{ matrix.ci_total }}
          CI_INDEX: ${{ matrix.ci_index }}


  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #
  #     - run: echo "Deploying ..."