name: CI

on:
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Building ..."

  test: 
    needs: build
    runs-on: ubuntu-latest

    steps:
        # This uses the actions/checkout action to clone your repository.
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          # sets up the specified Node version, and
          node-version: 22.x
          # caches npm dependencies to speed up the workflow.
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run unit-tests
        run: yarn test:ci

  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #
  #     - run: echo "Deploying ..."